name: anime_verse
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  go_router: ^16.2.4
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  http: ^1.6.0
  cached_network_image: ^3.4.1
  firebase_auth: ^6.1.2
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets: 
    - assets/images/

  fonts:
    - family: Urbanist
      fonts: 
        - asset: assets/fonts/Urbanist-Regular.ttf 
        -  asset: assets/fonts/Urbanist-Thin.ttf
           weight: 100
        -  asset: assets/fonts/Urbanist-Light.ttf
           weight: 300
        -  asset: assets/fonts/Urbanist-Medium.ttf
           weight: 500
        -  asset: assets/fonts/Urbanist-SemiBold.ttf
           weight: 600
        -  asset: assets/fonts/Urbanist-Bold.ttf
           weight: 700
        -  asset: assets/fonts/Urbanist-ExtraBold.ttf
           weight: 800

#App icon configuration
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/app_icon.png"
  adaptive icon background: "#FFFFFF"
  adaptive icon foreground: "assets/images/app_icon.png"

#Splash screen configuration
flutter_native_splash:
  android: true
  ios: false
  web: false
  color: "#FFFFFF"
  image: "assets/images/splash_screen_icon.png"
  android_12:
    color: "#FFFFFF"
    image: "assets/images/splash_screen_icon.png"